<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('items', function (Blueprint $table) {
            $table->increments('id');
            $table->text('type')->nullable();
            $table->text('name')->nullable();
            $table->text('serial_number')->nullable();
            $table->text('place')->nullable();
            $table->text('summary_one')->nullable();
            $table->text('summary_two')->nullable();
            $table->date('date')->nullable();
            $table->text('releasing')->nullable();
            $table->text('receiving')->nullable();
            $table->text('notes')->nullable();
            $table->text('more')->nullable();
            $table->timestamps();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('items');
    }
}
